### ISSUE TITLE
Apple Silicon cannot run RawFileReader

### ISSUE THREAD

**Issue by EstrellaXD** [thermofisherlsms/RawFileReader#18]
Thank you for update the `net8` `RawFileReader`, it runs normally on my x64 Linux Server. However, there're few problems when it comes to macOS(arm64).

First, I cannot load NET8 version `ThermoFisher.CommonCore.RawFileReader` and `ThermoFisher.CommonCore.MassPrecisionEstimator`, but other two module can be loaded successfully.

Error message below:
```
Traceback (most recent call last):
  File "/Users/estrella/Developer/MassSpec/RawFileReader/RawFileExacter/reader.py", line 25, in <module>
    clr.AddReference('ThermoFisher.CommonCore.RawFileReader')
System.IO.FileLoadException: Could not load file or assembly 'ThermoFisher.CommonCore.RawFileReader, Version=8.0.6.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Python.Runtime.AssemblyManager.LoadAssemblyPath(String name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/AssemblyManager.cs:line 245
   at Python.Runtime.CLRModule.AddReference(String name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/Types/ClrModule.cs:line 105
   at InvokeStub_CLRModule.AddReference(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

When I tried NET471 version, all modules can be loaded successfully, but there's also a bug like #3 . Raw file cannot be opened due to the path error.

And also, mono is not capitalized with arm64 python, so for now, arm64 can not use RawFileReader.

If you can fix this error, we will be very grateful.

**Comment by jshofstahl** [comment]
Please contact me at jim.shofstahl@thermofisher.com so that we can work through your issues.

**Comment by heejongkim** [comment]
Any update on this matter?

**Comment by jim-shofstahl** [comment]
Please use Visual Studio Code and then select either "Any CPU" or "x64" for the target platform.  We don't support the Arm64 target at this time.
